### ISSUE TITLE
Tenor Conference Question 

### ISSUE THREAD

**Issue by branlsnyder** [cmisra/SangeetTeX#1]
Are there any audio sources/references where I could hear this notation played/performed? I am unfamiliar with this music genre, and found your presentation at Tenor incredibly fascinating. As someone unfamiliar with this genre, I'm curious to learn more about how the music and notation are related.

**Comment by cmisra** [comment]
Thanks for your interest in this work. Please visit [tagoreweb.in](http://www.tagoreweb.in) for the resources. Here you can find the complete works of [Rabindranath Tagore](https://en.wikipedia.org/wiki/Rabindranath_Tagore) including songs which is your domain of interest. The songs section contains the lyrics, metadata like Raag and Taal, and the notation in scanned image format. The only problem is that the website is showing information in Bangla. Since Tagore is a cultural icon, you can find enough resources in other websites and YouTube as well.

**Comment by branlsnyder** [comment]
Thank you for sharing these! I appreciate that.
